enable_experimental: true
namespaces:
  - name: app1
    format: '$remote_addr - [$time_local] "$request" $status $body_bytes_sent rt=$request_time'
    histogram_buckets: [.1, .3, 1.5, 10.5]
    source:
      files:
        - /mnt/nginxlogs/access.log
    relabel_configs:
      - target_label: addr
        from: request
        split: 2
        matches:
          - regexp: '^(.*)$'
            replacement: '$1'
