version: '3.8'
services:
  web:
    image: nginx
    volumes:
      - ./templates:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'
  nginx-exporter:
    image: labbsr0x/nginx-monitor
    depends_on:
      - web
    ports:
      - '4040:4040'
    volumes:
      - ./templates:/mnt/nginxlogs
      - ./config.yml:/etc/prometheus-nginxlog-exporter.yml
    command: -config-file /etc/prometheus-nginxlog-exporter.yml
